### ISSUE TITLE
初始化兼容问题

### ISSUE THREAD

**Issue by Mecyu** [bingcool/swoolefy#9]
在不使用docker的情况下，mac系统不能兼容swoolefy的初始化安装（php swoolefy start App -dev）;
会报一些错，比如：mac系统的进程是不能重命名的，所以swoole_set_process_name的就需要判断一下系统才能执行，不然会报错；
又比如：不能在/dev/目录下创建新目录（我直接sudo mkdir也不可以创建），执行开始命令时也会报错；
docker没去尝试过，不知道以后有时间能不能尝试做下兼容（嘿嘿，刚觉swoolefy挺适合swoole初学者的）；
另外请教下，我是swoole新手，网上各类文章和例子都看了不少，也在一些php框架尝试使用了基础功能，但是总觉得缺少一些什么（感觉是在实际项目中要怎么嵌入swoole的使用，具体是什么挺模糊的，不知道兄弟们能明白我的这种感受吗？哈哈哈）
感谢指教！！！

**Comment by bingcool** [comment]
swoolefy一开始就不考虑支持mac系统，强烈要求开发环境与生产环境一致。
